### ISSUE TITLE
Add Su Squares

### ISSUE THREAD

**Issue by fulldecent** [0xProject/erc721-website#11]
Please add Su Squares / https://tenthousandsu.com/ to the site.

Here is the logo

![screen shot 2018-03-14 at 9 53 53 pm](https://user-images.githubusercontent.com/382183/37440717-52196972-27d4-11e8-80a8-a414b8997627.png)

**Comment by tomhschmidt** [comment]
Hey @fulldecent  -- feel free to submit a PR that adds your logo to the site and I'll review it.
