### ISSUE TITLE
CNAME fix

### ISSUE THREAD

**Issue by fulldecent** [0xProject/erc721-website#15]
- [x] Remove CNAME from repository root, this is no longer necessary, confirmed from discussion with GitHub.
- [x] Copy CNAME file from /docs to /source
- [ ] Confirm this was done correctly by ensuring that a run of `gulp dist` does not change /docs

**Comment by tomhschmidt** [comment]
Hey @fulldecent -- where did you see that the CNAME file isn't required? It was autogenerated by Github when I set up the custom domain for this site and it looks to be required. https://help.github.com/articles/troubleshooting-custom-domains/

Always happy to remove extra files though if it's not required

**Comment by fulldecent** [comment]
CNAME needs to be in the publishing root. Not the repo root. Source is this email from github:

![screen shot 2018-03-22 at 2 30 10 pm](https://user-images.githubusercontent.com/382183/37790668-9404fbc6-2ddd-11e8-9eff-c467c0e204a7.png)

**Comment by fulldecent** [comment]
Fixed in 8848a652a873f541a73a80400e260ef632c2629e
