### ISSUE TITLE
Add AlphaWallet as an ERC-721 SUPPORTER

### ISSUE THREAD

**Issue by zhangzhongnan928** [0xProject/erc721-website#43]
Link:
https://alphawallet.com
Logo
![alphawalletlogo](https://user-images.githubusercontent.com/33795543/49360483-41ca8c80-f714-11e8-94ac-bd514ba76be3.png)

![copy of designcrowd_667089_17486228_3105890_vector](https://user-images.githubusercontent.com/33795543/49360718-f82e7180-f714-11e8-8754-e2a88f32d34a.png)

**Comment by tomhschmidt** [comment]
Please make a PR

**Comment by zhangzhongnan928** [comment]
Will do
